check tex file formatting on a single job
Building the latex action takes a minute and a half for each job it triggers...

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -11,45 +11,27 @@ env:
                     # If you renamed your root tex file - originally "spellcards.tex" - (e.g. to get a different PDF name),
                     # simply also adjust the filename here.
 jobs:
-  list_tex_files:
-    # list all .tex files in this repo and save them in a variable that can be used by other jobs as input for their matrix (so they run one job on each tex file)
-    outputs:
-      matrix: ${{ steps.list-files.outputs.matrix }}
-    runs-on: [ubuntu-latest]
-    steps:
-      - name: checkout
-        uses: actions/checkout@v4
-      - name: list .tex files in this repo
-        id: list-files
-        # print each filename (relative path) as an element of a JSON list, github can parse this into setting output variable "matrix"
-        run: |
-          (
-            printf 'matrix={"include":['
-            # printing each file as a json element with trailing comma, then removing the last comma with sed. Tis is all in one line with the printfs:
-            find . -name "*.tex" -exec printf '{"file":"{}"},' \; | sed 's/,$//'
-            printf ']}\n'
-          ) >> $GITHUB_OUTPUT
   check_formatting:
-    # run latexindent on each tex file and diff the result with committed file. Produces failure of the formatting is not applied properly.
-    needs: [list_tex_files]
-    runs-on: [ubuntu-latest]
-    strategy:
-      # read the output variable of the list_tex_files job
-      matrix: ${{fromJson(needs.list_tex_files.outputs.matrix)}}
-      fail-fast: false
+    runs-on: ubuntu-latest
+    container:
+      image: danteev/texlive:latest
     steps:
       - name: Set up Git repository
         uses: actions/checkout@v4  # Checks-out repository under $GITHUB_WORKSPACE
-      - name: Apply indentation rules to ${{ matrix.file }}
-        # first format the content of the file and save this into a temporary file
-        uses: dante-ev/latex-action@latest
-        with:
-          root_file: ${{ matrix.file }}
-          compiler: latexindent
-          args: --local=src/.latexindent.yaml -o formatted.tex    # configuration is read from local files in git repository root. you can adjust here if your file is somewhere else.
-      - name: Check for correct formatting
-        # now compare this temporary file, which is correctly formatted, with the actual file. Any differences will be printed in screen and fail this job.
-        run: diff -u formatted.tex "${{ matrix.file }}"
+      - name: Check formatting of *.tex files
+        shell: bash        
+        run: |
+          set -euo pipefail
+          declare -i failures=0
+          while IFS= read -r file; do
+            if ! latexindent --silent -kv --local=src/.latexindent.yaml "$file"; then
+              failures+=1
+              # escape the filename for use in workflow commands (comma, colon and percent need escaping)
+              fileEscaped=$(echo "$file" | sed 's/,/%2C/g' | sed 's/:/%3A/g' | sed 's/%/%25/g')
+              printf "::error file=%s,line=1::Invalid formatting in '%s', please check logs\n" "${fileEscaped}" "$(basename "${file}")"
+            fi
+          done < <(find . -name "*.tex")
+          exit $((failures))
   lint_latex:
     # use chktex to scan the whole project for style issues that could later lead to problems
     runs-on: ubuntu-latest
